[formatting]
align_comments = true
array_trailing_comma = true
array_auto_expand = true
array_auto_collapse = true
compact_arrays = false
compact_inline_tables = false
inline_table_expand = true
compact_entries = false
column_width = 80
indent_tables = false
indent_entries = false
indent_string = "    "
trailing_newline = true
reorder_keys = true
reorder_arrays = true
reorder_inline_tables = true
allowed_blank_lines = 1
crlf = false
